all:
  children:
    app_servers:
      hosts:
        3.251.81.214:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/mshabade/cloud-infrastructure-automation-assessment/terraform/devops-tf-key.pem
